Roberta data reader
allenai/allennlp-models pull request #247
Opened 2021-04-07 23:17 UTC by jacob-morrison

Adding a dataset reader and training config for RoBERTa on SuperGLUE RTE

2021-04-13 22:03 UTC, dirkgr requested changes
Only small changes requested

2021-04-13 22:03 UTC, dirkgr commented on allennlp_models/pair_classification/dataset_readers/transformer_superglue_rte.py
> +        for relation in self.shard_iterable(jsonlines.open(file_path)):
Use https://github.com/allenai/allennlp/blob/main/allennlp/common/file_utils.py#L952, so we don't need a new dependency.

2021-04-13 22:03 UTC, dirkgr commented on training_config/pair_classification/superglue_rte_roberta.jsonnet
> +      "warmup_steps": 100
That's not a lot of warmup, but if you're getting the numbers, who am I to argue?

2021-04-15 21:22 UTC, jacob-morrison commented on allennlp_models/pair_classification/dataset_readers/transformer_superglue_rte.py
> +            instance = self.make_instance(index, label, premise, hypothesis)
Done

2021-04-15 21:23 UTC, jacob-morrison commented on training_config/pair_classification/superglue_rte_roberta.jsonnet
> +      "warmup_steps": 100
¯\_(ツ)_/¯

2021-04-15 21:24 UTC, jacob-morrison commented on allennlp_models/modelcards/pair-classification-roberta-rte.json
> +        "short_description": "A pair classification model patterned after the proposed model in Devlin et al, fine-tuned on the MultiNLI corpus",
Ah yeah fair point. I put MNLI because I used roberta-large-mnli like FB did, but I then technically finetuned that on RTE.

2021-04-16 16:11 UTC, dirkgr approved these changes

2021-04-16 16:11 UTC, merged